### ISSUE TITLE
Possibility to skip DB creation step

### ISSUE THREAD

**Issue by utterstep** [daaku/sqlx-pg-migrate#1]
Thanks very much for this lib, looks like something that would be of great help in my pet project :)
There is one small problem currently: `migrate` function starts with checking the existence of DB (https://github.com/daaku/sqlx-pg-migrate/blob/master/src/lib.rs#L144). It's doing so by connecting to `postgres` DB initially. Sadly, in my case I use managed Postgres solution from Yandex.Cloud, and it's prohibited there to access `postgres` DB by end-user. 

Is it possible to make "get-or-create DB" feature optional?
If that's the case, I can make a PR if you'd like any help :)
In that case it'd be helpful to get some guidance from you on how you seem this properly implemented: another `migrate` function? feature gate? breaking change to `migrate`, adding param, specifying desired behaviour?

Thanks again :)

**Comment by utterstep** [comment]
Here is example of possible implementation (https://github.com/utter-step/sqlx-pg-migrate/commit/77edc67105ccb9009e286ec968b3eb1c840ca334).
I pushed this to my fork to be able to use this in CI to solve the issue for myself at this point of time :)

**Comment by daaku** [comment]
No need for a feature. This is a perfectly fine thing to fix for everyone, it's a common enough problem. I had a TODO in there mentioning the same thing actually :smile: 

Fixed in `1.0.4`.

**Comment by utterstep** [comment]
Yay, thanks a lot! :)
